# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.219
neo_version_range=[21.1,)
loader_version_range=[4,)

## Mod Properties
mod_id=tinygates
mod_name=Tiny Gates
mod_license=GNU GENERAL PUBLIC LICENSE
mod_version=1.21.1-5.0.2
mod_group_id=com.dannyandson.tinygates
mod_authors=Danny
mod_description=Adds tiny redstone gate blocks and even very tiny gates that you can put on Tiny Redstone's panels to form tiny integrated circuits.
